# Generated by Django 4.2.3 on 2023-07-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
